server:
  port: "8080"
  language: "en"
  i18n_path: "../../i18n"

database:
  postgres_url: "${POSTGRES_URL}"

cors:
  allowed_origins:
    - "http://localhost:3000"
    - "https://example.com"
  allowed_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allowed_headers:
    - "Origin"
    - "Content-Type"
    - "Authorization"
  expose_headers:
    - "Content-Length"
  allow_credentials: true
  max_age: 43200 # in seconds (12 hours)