// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package initialize

import (
	"borrow_book/internal/handler"
	"borrow_book/internal/repository"
	"borrow_book/internal/router"
	"borrow_book/internal/service"
	"github.com/jmoiron/sqlx"
)

// Injectors from wire.go:

func InitializeApp(db *sqlx.DB) (*router.AppRouter, error) {
	bookRepository := repository.NewBookRepository(db)
	bookService := service.NewBookService(bookRepository)
	bookHandler := handler.NewBookHandler(bookService)
	authorRepository := repository.NewAuthorRepository(db)
	authorService := service.NewAuthorService(authorRepository)
	authorHandler := handler.NewAuthorHandler(authorService)
	borrowRepository := repository.NewBorrowRepository(db)
	borrowService := service.NewBorrowService(borrowRepository)
	borrowHandler := handler.NewBorrowHandler(borrowService)
	swaggerRouter := router.NewSwaggerRouter()
	appRouter := router.NewAppRouter(bookHandler, authorHandler, borrowHandler, swaggerRouter)
	return appRouter, nil
}
